export const REQUEST_REGISTER_USER = 'REQUEST_REGISTER_USER';
export const RECEIVE_REGISTER_USER = 'RECEIVE_REGISTER_USER';

export const REQUEST_CHAT = 'REQUEST_CHAT';
export const CHAT_STARTED = 'CHAT_STARTED';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const LEAVE_CHAT = 'LEAVE_CHAT';
export const CHAT_FINISHED = 'CHAT_FINISHED';
